apiVersion: v1
kind: Pod
metadata: 
  name: falco-probe-configurer
spec: 
  volumes:
    - name: var
      hostPath:
        path: /var
    - name: usr
      hostPath:
        path: /usr
    - name: lib
      hostPath:
        path: /lib
    - name: etc
      hostPath:
        path: /etc
  containers:
    - name: probe-loader
      image: nithishdev/kernel-headers-installer:centos-stream8
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: var
          mountPath: /var
        - name: usr
          mountPath: /usr
        - name: lib
          mountPath: /lib
        - name: etc
          mountPath: /etc




