apiVersion: v1
kind: Pod
metadata: 
  name: kernel-headers-installer
spec: 
  volumes:
    - name: var
      hostPath:
        path: /var
    - name: usr
      hostPath:
        path: /usr
    - name: lib
      hostPath:
        path: /lib
    - name: etc
      hostPath:
        path: /etc
  containers:
    - name: 


