apiVersion: v1
kind: Service
metadata:
  name: syscalls-tracer
  namespace: kubesecgen
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: syscalls-tracer
  ports:
  - name: syscalls-tracer-server
    protocol: TCP
    port: 98429
    targetPort: 98429
